
[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/enrich"
  to = "/.netlify/functions/enrich"
  status = 200


[[redirects]]
  from = "/api/health"
  to = "/.netlify/functions/health"
  status = 200
